{% set version = "4.9.2" %}

package:
  name: pydash
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pydash/pydash-{{ version }}.tar.gz
  sha256: 11d8f3c92d92a004e042fdb226b10dba28f4e311546b0de89d983e91539d5e55

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pydash
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dgilland/pydash
  license: MIT
  license_file: LICENSE.rst
  summary: The kitchen sink of Python utility libraries for doing "stuff" in a functional way.
  description: The kitchen sink of Python utility libraries for doing stuff in a functional way. Based on Lo-Dash JS library
  doc_url: https://pydash.readthedocs.io/en/latest/
  dev_url: https://github.com/dgilland/pydash

extra:
  recipe-maintainers:
    - souravsingh
    - dbast
