{% set version = "7.0.6" %}

package:
  name: pydash
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pydash/pydash-{{ version }}.tar.gz
  sha256: 7d9df7e9f36f2bbb08316b609480e7c6468185473a21bdd8e65dda7915565a26

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.7
    - typing_extensions

test:
  imports:
    - pydash
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dgilland/pydash
  license: MIT
  license_file: LICENSE.rst
  summary: The kitchen sink of Python utility libraries for doing "stuff" in a functional way.
  description: The kitchen sink of Python utility libraries for doing stuff in a functional way. Based on Lo-Dash JS library
  doc_url: https://pydash.readthedocs.io/en/latest/
  dev_url: https://github.com/dgilland/pydash

extra:
  recipe-maintainers:
    - souravsingh
    - dbast
