{% set version = "5.1.2" %}

package:
  name: pydash
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pydash/pydash-{{ version }}.tar.gz
  sha256: 0556062f6583c21fa70dd9a2c1a4e63bbe8cd54e14fecdfb579b46c36d93836f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=2.7

test:
  imports:
    - pydash
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dgilland/pydash
  license: MIT
  license_file: LICENSE.rst
  summary: The kitchen sink of Python utility libraries for doing "stuff" in a functional way.
  description: The kitchen sink of Python utility libraries for doing stuff in a functional way. Based on Lo-Dash JS library
  doc_url: https://pydash.readthedocs.io/en/latest/
  dev_url: https://github.com/dgilland/pydash

extra:
  recipe-maintainers:
    - souravsingh
    - dbast
