{% set name = "pydash" %}
{% set version = "4.6.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "16fb11da042359c2b0c7915b1ba6dd8a18e9e1002aa9e591bffec6af400edb28" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: python
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pydash

about:
  home: https://github.com/dgilland/pydash
  license: MIT
  license_file: LICENSE.rst
  summary: The kitchen sink of Python utility libraries for doing "stuff" in a functional way. 
  description: "The kitchen sink of Python utility libraries for doing stuff in a functional way. Based on Lo-Dash JS library"
  doc_url: https://pydash.readthedocs.io/en/latest/
  dev_url: https://github.com/dgilland/pydash

extra:
  recipe-maintainers:
    - souravsingh
