travis:
  secure:
    BINSTAR_TOKEN: b1arqDiBDuCH7AK1kBeYCFxSb4WD222qeRB6ccAX+R4FT89fxLP0y9++dOEAMoMTFmtmM6qGh1X+54tERPwUzVh7+t80/6c01currQXb3qJJ5ZO4WMmD150nmBk0NHkeTqdrDiIT9fLGb8AlUbd7HX2DdpCclFh22IpmawTY19gsQIkcoJMs2Qz0AghTMbyUt9Zh6JMexSRsdWdZghJLnSyIaKofRcSz4gM/B+AHNm8PdWjrUacuCUIvWXSON1hpa7Ls12V01i5/eEFdFLcKptVj1XDTfDXTMCPPkeDKLBZmx1mEeIQt22wfBWGAEcI2XdTap8QkgU9YKOTbh/SN1aSq/RxK5fFdsdC8XCYEYmDAxXUXivoKXhSOi4wzctMPh5o9CQu8hMVjJWs1+z2TboAe8oYLaUs8YrM4M6ZSmhlriYzxxTieCOi2cgVF5TcDPUF+AezCQctu+Qgg7V7DWZ1FilUBRPo4XyDKzvMuU/dI/l1S3oaOa0TdFKpFyM1VuTC/T8+JEIwNIw2O0WF/CXMuUkbtWcAT5mqYxUhQkFd+zP5G03fG23bzaQZIczVUIp4/lox0W1scf02xc2qaSehm9ga6KDfiwK6YmRBSKKCltex21nbNqYYJ4DNvgFOuhF1CMFD5gkNoqqovE0x6e4Iy75t2ELFQMt/8D/VcXtI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
