travis:
  secure:
    BINSTAR_TOKEN: oWMC7gHPI6j2O4+2UxVCNdZtG70NCtikUwP7PHsEGnECS9J+rsfwIND24uHPblOkKvr4kZ+6yFRrNCySKFailj1N5yzg1KoSx9nBWdLk4EJn4Y37MnH2YSO54X9xrYTA4I58Y8cj8+oD+Uxo0swWG8ZE3QK5WPD3f/v1QIOIRKA+oaY+c1n2tf3CaIli553Uth3cTeS0hIbtLqcFfz+tcytFqsdwM3EoLjjqhlyPHPjxOQvhz9buLknx3qxW2gOqk6JOCw9NShdxS3bjw1cba3JdaJcQCeM6SV7WLP3SpkJO82ZNgmEAqoUWpGQCgl3yBvFTiPkXByptOpFUbBBUbPiejnUByC7lpit65i6FZOjZ5mMWw3MDXLtAcmfPohbTqiIzqpGuCqisTpMkLqGAa9zJYznHbi2HV78rMHe6MEjOcb642+j4RogDcByy/zJ2W2SlEAXsXqWIVjlvkDv0WO92PCubGKUgkZQJT4a6fvko8NqsEASVMInoVYLv8DGbNq8d3zVbMktgHaTRehrE8RvEpeKieykyn4QbBzk0VW2z8dWYHfibhmksy5nSpKzEMz5bQrVL+QAdtcbbMeVZtjOXlyetdQo3SsVCun4KfbHksnxMyecDFcmmRdYcQfez0jIQpsE2KKJHCrWnZTOSZDCCNs7HUwFT2yB9NYq7H7k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
